version: '3'
services:
  strapi-v4:
    build: 
      context: strapi-debian/
      args:
        NODE_VERSION: 16
        STRAPI_VERSION: 4.2.2
    restart: always
    container_name: strapi-v4
    ports:
      - '1337:1337'
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SSL: false # boolean for SSL.
    volumes:
      - ./datastore/source-app:/srv/app # create a new project in app volume
  postgres:
    restart: always
    image: postgres:14.4
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - ./datastore/datastore-pg:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v0.28.0rc1
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./datastore/datastore-ms:/data.ms
  bucketstore-minio:
      image: quay.io/minio/minio:RELEASE.2022-06-30T20-58-09Z
      command: server --console-address ":9001" /data
      expose:
        - "9000"
      ports:
        - 9001
      # environment:
        # MINIO_ROOT_USER: minioadmin
        # MINIO_ROOT_PASSWORD: minioadmin
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
      volumes: 
        - ./datastore/bucketstore-minio:/data
volumes:
  data:
  app:
